/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PuzzleIndexImport } from './routes/puzzle/index'
import { Route as PuzzlePuzzleIdImport } from './routes/puzzle/$puzzleId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PuzzleIndexRoute = PuzzleIndexImport.update({
  id: '/puzzle/',
  path: '/puzzle/',
  getParentRoute: () => rootRoute,
} as any)

const PuzzlePuzzleIdRoute = PuzzlePuzzleIdImport.update({
  id: '/puzzle/$puzzleId',
  path: '/puzzle/$puzzleId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/puzzle/$puzzleId': {
      id: '/puzzle/$puzzleId'
      path: '/puzzle/$puzzleId'
      fullPath: '/puzzle/$puzzleId'
      preLoaderRoute: typeof PuzzlePuzzleIdImport
      parentRoute: typeof rootRoute
    }
    '/puzzle/': {
      id: '/puzzle/'
      path: '/puzzle'
      fullPath: '/puzzle'
      preLoaderRoute: typeof PuzzleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/puzzle': typeof PuzzleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/puzzle': typeof PuzzleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdRoute
  '/puzzle/': typeof PuzzleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/puzzle/$puzzleId' | '/puzzle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/puzzle/$puzzleId' | '/puzzle'
  id: '__root__' | '/' | '/puzzle/$puzzleId' | '/puzzle/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PuzzlePuzzleIdRoute: typeof PuzzlePuzzleIdRoute
  PuzzleIndexRoute: typeof PuzzleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PuzzlePuzzleIdRoute: PuzzlePuzzleIdRoute,
  PuzzleIndexRoute: PuzzleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/puzzle/$puzzleId",
        "/puzzle/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/puzzle/$puzzleId": {
      "filePath": "puzzle/$puzzleId.tsx"
    },
    "/puzzle/": {
      "filePath": "puzzle/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
